export const TOPICS = [
  "a coffee shop that's only open at night",
  'a neighborhood tool-sharing library',
  'a better way to meet your neighbors',
  'a restaurant with no fixed menu',
  'a community garden for apartment dwellers',
  'a service that makes moving less stressful',
  'a screen-free social club for adults',
  'a new kind of public playground',
  'a subscription for learning practical skills',
  'a marketplace for unfinished creative projects',
  'a way to make airports more enjoyable',
  'a pop-up experience for rainy days',
  'a business that brings empty storefronts to life',
  'a better school lunch program',
  'a product that helps people sleep better',
  'a festival designed for introverts',
  'a service for sharing family recipes',
  'a more useful loyalty program',
  'a library that lends more than books',
  'a new ritual for starting the workday',
  'a way to reduce food waste at home',
  'a travel experience for your own city',
  'a social network without follower counts',
  'a business built around repairing old things',
  'a better waiting-room experience',
  'a product that makes chores feel rewarding',
  'a community event that happens before sunrise',
  'a new use for abandoned parking lots',
  'a service that helps friends plan trips',
  'a more humane job interview process',
  'a store where nothing is permanently for sale',
  'a way for grandparents to share their stories',
  'a tiny business that can run from a bicycle',
  'a better experience for first-time pet owners',
  'a club for people learning something from scratch',
  'a product for making small spaces feel bigger',
  'a neighborhood tradition people would anticipate all year',
  'a service that turns errands into adventures',
  'a new kind of museum for everyday objects',
  'a business that only operates one day a week',
  'a way to make local government easier to understand',
  'a restaurant designed around conversation',
  'a tool that helps people finish side projects',
  'a community space inside a train station',
  'a better way to welcome new employees',
  'a product that encourages spontaneous creativity',
  'a service for celebrating small milestones',
  'a new experience for long-distance friendships',
  'a business that makes winter more fun',
  'a public space designed for doing absolutely nothing',
];

export function randomTopic(currentTopic) {
  const choices = TOPICS.filter(topic => topic !== currentTopic);
  return choices[Math.floor(Math.random() * choices.length)];
}
